version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000

  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
