version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - default
    command: npm run dev
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - default
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongo
      - redis
    restart: on-failure

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  default:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
